spring:
  application:
    name: MyProfileApp
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
application:
  mail:
    from:
      address: ${MAIL_FROM_ADDRESS}
  recaptcha:
    secret:
      key: ${RECAPTCHA_SECRET_KEY}
    site:
      key: ${RECAPTCHA_SITE_KEY}